### ISSUE TITLE
Bulleted Option for Ingredients

### ISSUE THREAD

**Issue by aripatrick** [lachholden/obsidian-recipe-view#22]
I'm using the Minimal theme by kepano and the ingredients list does not appear with the same nice spacing between ingredients that your example images have. Below is a screenshot of what things look like on my end:

<img width="293" alt="Screenshot 2024-03-26 at 11 57 28" src="https://github.com/lachholden/obsidian-recipe-view/assets/932694/ba350bd7-6d06-4cd2-8792-73c38c6deae9">

Perhaps this is just a side effect of the theme, but it makes reading the ingredients list more difficult. If solving for this particular theme is not practical, I was wondering if a more global solution could be having an option to display ingredients as bullet points. I believe implementing this would resolve the readability issue for me.

**Comment by lachsh** [comment]
I changed the default spacing since taking the screenshots in the README, so now it will always match the theme. I've added an option to force bullets in two-column mode, which will be present in the next release. The bullets will go into the margin and the text will remain aligned as-is so as to not waste horizontal space in the already narrow side column.
