### ISSUE TITLE
Is it possible to add a timer?

### ISSUE THREAD

**Issue by Eneswar** [lachholden/obsidian-recipe-view#9]
If you have a time in the recipe, lets say 20 minutes, is there a way to turn that into a timer, you click it and it counts down or somethign like that?

**Comment by lachholden** [comment]
This is something I was considering, but ultimately have probably decided not to include for now. This is because there's not really any way to ring a timer or even send a notification (at least on mobile) if the app is closed. I'd be more likely to add the ability to specify some kind of URL scheme to create a timer in a different timer app I think.

Open to being persuaded if you think having it entirely within Obsidian would be useful, though!

**Comment by Eneswar** [comment]
Tbh I looked it up some time ago and from what I found, the only way seemed to be to add a time via a iframe, which imo wouldnt fit. So it might be for the better to leave it out. Btw any word when this gets approved? I need this in my main vault :P

**Comment by lachholden** [comment]
No word unfortunately, the plugin was reviewed once and I've made the changes requested. It's just a matter now of waiting until it gets reviewed again. :)

**Comment by lachholden** [comment]
@Eneswar if you follow this pull request, then as soon as it gets merged you should be able to download it from the community plugins list: https://github.com/obsidianmd/obsidian-releases/pull/2432
